!$THEME = "vdb"

<style>

--vdbWhite #fff  
--vdbBlue #113e67  
--vdbGreen #2bebce  
--vdbLightGreen #d5fbf5

root {  
    FontName Arial  
    FontColor var(--vdbBlue)  
}

actor {  
    BackGroundColor: var(--vdbGreen)  
    LineColor var(--vdbGreen)  
}

arrow {  
    LineThickness 1.5  
    LineColor var(--vdbGreen)  
}

note {  
    FontColor var(--vdbWhite)  
    BackGroundColor: var(--vdbBlue)  
    LineThickness 0.5  
    LineColor var(--vdbLightGreen)  
}

package {  
    title {  
        FontStyle bold  
        FontColor var(--vdbBlue)

        BackGroundColor: var(--vdbLightGreen)  
    }

    LineColor var(--vdbBlue)  
}

usecase {  
    LineColor var(--vdbGreen)  
    BackGroundColor: var(--vdbLightGreen)  
}

</style>
